# Generated by Django 4.0.6 on 2022-09-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_is_confirmed_order_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='paid', max_length=10),
        ),
    ]
