# Generated by Django 4.0.6 on 2022-09-15 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_discount_is_finished_alter_discount_product'),
        ('events', '0003_advertisement'),
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='count',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.couponhold'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='method',
            field=models.CharField(default='CARD', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='used_point',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.discount')),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productoption')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
