# Generated by Django 4.0.6 on 2022-09-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='상품 외 2건', max_length=30),
            preserve_default=False,
        ),
    ]
