# Generated by Django 4.0.6 on 2022-09-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_delivery_remove_order_status_deliverytracking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='courier_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
