# Generated by Django 4.0.6 on 2022-09-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_delivery_is_done_alter_delivery_courier_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='paid', max_length=10),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='tracking_level',
            field=models.IntegerField(default=1),
        ),
    ]
