# Generated by Django 4.0.6 on 2022-09-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_status_alter_delivery_tracking_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(default='paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliverytracking',
            name='kind',
            field=models.CharField(max_length=30),
        ),
    ]
