# Generated by Django 4.0.6 on 2022-10-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_delivery_status_alter_deliverytracking_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
