# Generated by Django 4.0.6 on 2022-10-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_delivery_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='level',
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
