# Generated by Django 4.0.6 on 2022-10-04 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_delivery_level_deliverytracking_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='status',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='tracking_level',
        ),
    ]
