# Generated by Django 4.0.6 on 2022-10-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_payment_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
