# Generated by Django 4.0.6 on 2022-10-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_is_payment_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='invoice_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
