# Generated by Django 4.1.3 on 2022-11-30 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_profile_backdrop_image_alter_profile_profile_image'),
        ('events', '0003_advertisement'),
        ('products', '0021_alter_review_order_product'),
        ('orders', '0018_alter_order_address_alter_order_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='is_review_written',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.couponhold'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.discount'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productoption'),
        ),
    ]
