# Generated by Django 4.1.3 on 2022-11-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_orderproduct_is_review_written_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='결제 대기', max_length=20),
        ),
    ]
