# Generated by Django 4.1.3 on 2022-12-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='recipient_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
