version: "0.1"

services:
  django:
    container_name: django
    build: server
    command: gunicorn --bind 0.0.0.0:8000 server.wsgi:application
    expose:
      - "8000"

  nginx:
    container_name: nginx
    build: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
