version: "3.7"

services:
  django:
    container_name: django
    build: server
    command: gunicorn --bind 0.0.0.0:8000 --access-logfile /logs/access.log --error-logfile /logs/error.log server.wsgi.staging:application
    volumes:
      - logs:/logs
      - media:/media
      - static:/static
    env_file:
      - server/.env
    expose:
      - "8000"

  nginx:
    container_name: nginx
    build: nginx
    volumes:
      - media:/media
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  media:
  static:
  logs: