# Generated by Django 4.0.6 on 2022-08-01 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_maincategory_color'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponhold',
            old_name='user',
            new_name='profile',
        ),
        migrations.AddField(
            model_name='couponcoverage',
            name='coupon',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.coupon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='couponcoverage',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
