# Generated by Django 4.0.6 on 2022-08-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_user_couponhold_profile_couponcoverage_coupon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('backdrop_image', models.ImageField(upload_to='events/banner')),
                ('link', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
