# Generated by Django 4.1.3 on 2022-11-30 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_rename_basket_profile_baskets_and_more'),
        ('events', '0003_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponhold',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='accounts.profile'),
        ),
    ]
