# Generated by Django 4.0.6 on 2022-10-14 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_inquiryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryimage',
            name='inquiry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.inquiry'),
        ),
    ]
