# Generated by Django 4.0.6 on 2022-10-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_inquiryimage_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inquiry/%Y/'),
        ),
        migrations.DeleteModel(
            name='InquiryImage',
        ),
    ]
