# Generated by Django 4.0.6 on 2022-10-18 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_inquiry_image_delete_inquiryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='image',
        ),
        migrations.CreateModel(
            name='InquiryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inquiry/%Y/')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.inquiry')),
            ],
        ),
    ]
