# Generated by Django 4.1.3 on 2022-12-06 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_inquiry_image_inquiryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryimage',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.inquiry'),
        ),
    ]
