# Generated by Django 4.0.6 on 2022-07-18 05:09

from django.db import migrations, models
import django.db.models.deletion
import server.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productsale_productoption_productimages'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('is_purchase', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            bases=(server.mixins.BaseMixins, models.Model),
        ),
        migrations.AddField(
            model_name='profile',
            name='bucket',
            field=models.ManyToManyField(through='accounts.Bucket', to='products.product'),
        ),
        migrations.AddField(
            model_name='bucket',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.profile'),
        ),
    ]
