# Generated by Django 4.0.6 on 2022-08-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_address_memo_alter_bucket_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.CharField(default='string', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default='010-9995-5728', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='recipient',
            field=models.CharField(default='string', max_length=30),
            preserve_default=False,
        ),
    ]
