# Generated by Django 4.0.6 on 2022-08-01 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_address_address_address_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='is_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='point',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='accounts.profile'),
        ),
    ]
