# Generated by Django 4.0.6 on 2022-08-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_point_is_use_profile_point_alter_point_profile'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='address',
            name='unique_priority',
        ),
        migrations.RemoveField(
            model_name='address',
            name='priority',
        ),
        migrations.AddField(
            model_name='address',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
