# Generated by Django 4.0.6 on 2022-08-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_profile_follower_remove_profile_following_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='created',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='updated',
        ),
    ]
