# Generated by Django 4.0.6 on 2022-08-12 08:44

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_follow_created_remove_follow_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('follower', 'following'), name='unique_follow'),
        ),
    ]
