# Generated by Django 4.0.6 on 2022-08-12 10:17

from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_post_backdrop_image'),
        ('accounts', '0013_profile_scrapped_alter_follow_follower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='scrapped',
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='scrap',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('profile', 'post'), name='unique_scrap'),
        ),
    ]
