# Generated by Django 4.0.6 on 2022-08-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_profile_scrapped_scrap_scrap_unique_scrap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrap',
            name='post',
        ),
        migrations.RemoveField(
            model_name='scrap',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='follower',
            field=models.ManyToManyField(related_name='+', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='+', to='accounts.profile'),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Scrap',
        ),
    ]
