# Generated by Django 4.0.6 on 2022-08-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_post_backdrop_image_post_hits'),
        ('accounts', '0015_remove_scrap_post_remove_scrap_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='scrapped',
            field=models.ManyToManyField(related_name='+', to='communities.post'),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
