# Generated by Django 4.0.6 on 2022-08-31 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_review_product'),
        ('accounts', '0016_profile_scrapped_alter_bucket_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bucket',
        ),
        migrations.AddField(
            model_name='profile',
            name='basket',
            field=models.ManyToManyField(related_name='+', through='accounts.Basket', to='products.product'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wish',
            field=models.ManyToManyField(related_name='+', through='accounts.WishList', to='products.product'),
        ),
        migrations.DeleteModel(
            name='Bucket',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='basket',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.profile'),
        ),
    ]
