# Generated by Django 4.1.3 on 2022-11-30 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_profile_backdrop_image_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='basket',
            new_name='baskets',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='scrapped',
            new_name='scraps',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='wish',
            new_name='wishes',
        ),
    ]
