# Generated by Django 4.1.3 on 2023-01-06 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_customproduct_image'),
        ('accounts', '0023_rename_basket_profile_baskets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='product',
        ),
        migrations.AddField(
            model_name='basket',
            name='custom_product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.customproduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='baskets',
            field=models.ManyToManyField(related_name='+', through='accounts.Basket', to='products.customproduct'),
        ),
    ]
