# Generated by Django 4.1.3 on 2023-01-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0013_alter_comment_comment_alter_comment_post'),
        ('accounts', '0024_remove_basket_product_basket_custom_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='scraps',
            field=models.ManyToManyField(related_name='scraps', to='communities.post'),
        ),
    ]
