# Generated by Django 4.1.3 on 2022-12-27 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_rename_basket_profile_baskets_and_more'),
        ('search', '0002_alter_search_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
            preserve_default=False,
        ),
    ]
