# Generated by Django 4.0.6 on 2022-07-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backdrop_image', models.ImageField(blank=True, null=True, upload_to='banner')),
            ],
        ),
        migrations.AddField(
            model_name='maincategory',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
