# Generated by Django 4.0.6 on 2022-07-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_banner_maincategory_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='color',
            field=models.CharField(default='#DDDDDD', max_length=10),
        ),
    ]
