# Generated by Django 4.0.6 on 2022-08-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_review_product_review_order_alter_review_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_write',
            field=models.BooleanField(default=False),
        ),
    ]
