# Generated by Django 4.0.6 on 2022-11-23 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_review_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_write',
        ),
    ]
