# Generated by Django 4.0.6 on 2022-11-28 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_order_profile'),
        ('products', '0015_alter_review_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='order',
        ),
        migrations.AddField(
            model_name='review',
            name='order_product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.orderproduct'),
            preserve_default=False,
        ),
    ]
