# Generated by Django 4.1.3 on 2022-11-29 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_order_profile'),
        ('products', '0017_remove_review_product_alter_review_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='review',
            name='order_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.orderproduct'),
        ),
    ]
