# Generated by Django 4.1.3 on 2022-11-29 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_rename_description_review_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='order_product',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
