# Generated by Django 4.1.3 on 2022-11-29 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_profile_backdrop_image_alter_profile_profile_image'),
        ('orders', '0018_alter_order_address_alter_order_profile'),
        ('products', '0019_remove_review_order_product_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AddField(
            model_name='review',
            name='order_product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.orderproduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='accounts.profile'),
        ),
    ]
