# Generated by Django 4.1.3 on 2022-11-29 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_order_address_alter_order_profile'),
        ('products', '0020_remove_review_product_review_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='order_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.orderproduct'),
        ),
    ]
