# Generated by Django 4.1.3 on 2022-12-01 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_productviewcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productviewcount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_count', to='products.product'),
        ),
    ]
