# Generated by Django 4.1.3 on 2022-12-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='url',
        ),
        migrations.AddField(
            model_name='content',
            name='path',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
