# Generated by Django 4.1.3 on 2023-01-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_customimage_delete_customimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customproduct',
            name='image',
            field=models.ImageField(null=True, upload_to='custom_product/%Y-%m'),
        ),
    ]
