# Generated by Django 4.1.3 on 2023-01-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_customproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customproduct',
            name='image',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
