# Generated by Django 4.1.3 on 2023-01-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_customproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='is_remove',
            field=models.BooleanField(default=False),
        ),
    ]
