# Generated by Django 4.1.3 on 2023-01-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_customimage_is_remove'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproduct',
            name='png_image',
            field=models.ImageField(null=True, upload_to='custom_product/%Y-%m'),
        ),
    ]
