# Generated by Django 4.1.3 on 2023-01-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_customproduct_png_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customproduct',
            name='png_image',
        ),
    ]
