# Generated by Django 4.1.3 on 2023-01-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_remove_customproduct_png_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_svg',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
