# Generated by Django 4.1.3 on 2023-01-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_product_default_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rendering',
            field=models.FileField(null=True, upload_to='product/3d'),
        ),
    ]
