# Generated by Django 4.0.6 on 2022-08-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='backdrop_image',
            field=models.ImageField(blank=True, null=True, upload_to='community/%Y-%m'),
        ),
    ]
