# Generated by Django 4.0.6 on 2022-10-19 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_post_backdrop_image_post_hits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='image',
        ),
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='community/%Y-%m')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.content')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.tag')),
            ],
        ),
    ]
