# Generated by Django 4.1.3 on 2022-12-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_remove_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentimage',
            name='tag',
        ),
    ]
