# Generated by Django 4.1.3 on 2022-12-28 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='content',
            new_name='post',
        ),
    ]
