# Generated by Django 4.1.3 on 2022-12-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0010_rename_content_postimage_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
    ]
