# Generated by Django 4.1.3 on 2022-12-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0011_remove_postimage_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='backdrop_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
