# Generated by Django 4.0.6 on 2022-07-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(upload_to='brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='backdrop_image',
            field=models.ImageField(upload_to='product/%Y-%m'),
        ),
    ]
